import fc from 'fast-check';
import { describe, expect, it } from 'vitest';
import {
  buildCsvExport,
  canChangeSyntheticFlag,
  csvEscape,
  DATASET_TYPES,
  provenanceInfo,
  ROLE_CODES,
  SAMPLE_DATA_MARKER,
  type CsvExportInput,
} from '../src/index.js';

const cell = fc.oneof(
  fc.string({ maxLength: 12 }),
  fc.constantFrom('a,b', 'say "hi"', 'line\nbreak', '=SUM(A1)', ' spaced ', ''),
);

const exportArb: fc.Arbitrary<CsvExportInput> = fc.record({
  title: fc.string({ minLength: 1, maxLength: 20 }),
  generatedAt: fc.constant('2026-09-30T08:00:00.000Z'),
  generatedBy: fc.constant('ana@smretail.com'),
  sampleData: fc.boolean(),
  meta: fc.array(fc.tuple(fc.string({ minLength: 1, maxLength: 10 }), cell), { maxLength: 3 }),
  columns: fc.array(cell, { minLength: 1, maxLength: 5 }),
  rows: fc.array(fc.array(cell, { maxLength: 5 }), { maxLength: 10 }),
});

describe('P9 provenance: sample-data marker on every export', () => {
  it('the first line is the SAMPLE DATA marker exactly when synthetic data is in use', () => {
    fc.assert(
      fc.property(exportArb, (input) => {
        const csv = buildCsvExport(input);
        const firstLine = csv.split('\r\n')[0];
        if (input.sampleData) {
          expect(firstLine).toBe(SAMPLE_DATA_MARKER);
        } else {
          expect(firstLine).not.toBe(SAMPLE_DATA_MARKER);
          expect(csv.startsWith(SAMPLE_DATA_MARKER)).toBe(false);
        }
      }),
    );
  });

  it('keeps the header block (title, time, user) and one line per data row', () => {
    fc.assert(
      fc.property(
        exportArb.filter((i) => [i.title, ...i.meta.flat(), ...i.columns, ...i.rows.flat()].every((c) => !/[\r\n]/.test(c))),
        (input) => {
          const lines = buildCsvExport(input).split('\r\n');
          const offset = input.sampleData ? 1 : 0;
          expect(lines[offset]).toBe(`${csvEscape('Export')},${csvEscape(input.title)}`);
          expect(lines).toContain(`Generated at,${input.generatedAt}`);
          expect(lines).toContain(`Generated by,${input.generatedBy}`);
          // header block + blank line + column header + rows + trailing empty
          expect(lines.length).toBe(offset + 3 + input.meta.length + 1 + 1 + input.rows.length + 1);
        },
      ),
    );
  });

  it('neutralises spreadsheet formulas and quotes separators', () => {
    expect(csvEscape('=SUM(A1)')).toBe("'=SUM(A1)");
    expect(csvEscape('+1')).toBe("'+1");
    expect(csvEscape('a,b')).toBe('"a,b"');
    expect(csvEscape('say "hi"')).toBe('"say ""hi"""');
    expect(csvEscape('plain')).toBe('plain');
  });
});

describe('provenanceInfo', () => {
  it('sampleData is true exactly when some in-use dataset is synthetic', () => {
    fc.assert(
      fc.property(
        fc.array(fc.record({ type: fc.constantFrom(...DATASET_TYPES), synthetic: fc.boolean() }), { maxLength: 6 }),
        (inUse) => {
          const info = provenanceInfo(inUse);
          expect(info.sampleData).toBe(inUse.some((d) => d.synthetic));
          expect([...info.syntheticDatasetTypes].sort()).toEqual(
            [...new Set(inUse.filter((d) => d.synthetic).map((d) => d.type))].sort(),
          );
        },
      ),
    );
  });
});

describe('Req 17.6: only a Rules Steward clears the synthetic flag', () => {
  it('clearing is allowed for RST only; a no-op change is always refused', () => {
    fc.assert(
      fc.property(fc.constantFrom(...ROLE_CODES), fc.boolean(), fc.boolean(), (role, from, to) => {
        const allowed = canChangeSyntheticFlag(role, from, to);
        if (from === to) expect(allowed).toBe(false);
        else if (from && !to) expect(allowed).toBe(role === 'RST');
        else expect(allowed).toBe(role === 'RST');
      }),
    );
  });

  it('a role that is not RST can never end with a cleared flag', () => {
    fc.assert(
      fc.property(fc.constantFrom(...ROLE_CODES.filter((r) => r !== 'RST')), (role) => {
        expect(canChangeSyntheticFlag(role, true, false)).toBe(false);
      }),
    );
  });
});
